frontend:
  image: dongjie66/frontend
  tag: 410581a
  autoscaling:
    averageUtilization: 90
backend:
  image: dongjie66/backend
  tag: 410581a
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
